version: '2'
services:
    myservicedemo-app:
        image: myservicedemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myservicedemo-mysql:3306/myservicedemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    myservicedemo-mysql:
        extends:
            file: mysql.yml
            service: myservicedemo-mysql
